// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBy2RF_TPkZyQZ7e5OIkcQmyXRUP3hHxt8',
    appId: '1:197699973316:web:6351fa680855558ffa5991',
    messagingSenderId: '197699973316',
    projectId: 'adhd-77c0f',
    authDomain: 'adhd-77c0f.firebaseapp.com',
    storageBucket: 'adhd-77c0f.firebasestorage.app',
    measurementId: 'G-P2K83YMMMF',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBAHdrODkZYk0VsQGuOueb7t4m9cy6Ib18',
    appId: '1:197699973316:android:3adf302c7e5619cffa5991',
    messagingSenderId: '197699973316',
    projectId: 'adhd-77c0f',
    storageBucket: 'adhd-77c0f.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBrepgNah7vdAVz4BfeegeQROUObAAqmMs',
    appId: '1:197699973316:ios:678bf04acb20073bfa5991',
    messagingSenderId: '197699973316',
    projectId: 'adhd-77c0f',
    storageBucket: 'adhd-77c0f.firebasestorage.app',
    iosBundleId: 'com.example.nn',
  );
}
